/** 地理叙事锚点。社区点位不是测量控制点；点间连接绝非 GPS 轨迹。 */
export const MAP_BOUNDS = { west:107.34, east:107.83, north:34.05, south:33.83 } as const;
export type Coordinate = { lon:number; lat:number };
export type Landmark = { id:string; name:string; english:string; coordinate:Coordinate; elevation:number; kind:string; title:string; body:string; look:string; transition:string; sources:{label:string;url:string}[]; coordinateNote:string };
const forestry={label:'国家林草局 · 太白山地貌',url:'https://www.forestry.gov.cn/c/www/ztq/13099.jhtml'};
export const LANDMARKS:readonly Landmark[]=[
 {id:'aoshan',name:'鳌山',english:'AO SHAN',coordinate:{lon:107.41925,lat:33.94223},elevation:3476,kind:'西端 · 从这里认识鳌太',title:"从鳌山出发，\n把目光交给东方。",body:'鳌太，不是一座山的名字。这段主脊连接西侧的鳌山与东侧的太白山。先记住眼前这个西端锚点，之后的地点便有了来路。',look:'在全貌中比较两端位置。下一站麦秸岭在鳌山东侧，导览将沿这个方向展开。',transition:'离开西端，认识麦秸岭。地图移动展示地点关系，不模拟实际步道。',sources:[{label:'PeakWiki · 鳌山点位',url:'https://www.peakwiki.org/en/peak.php?pid=352'},{label:'鳌太主脊地理介绍',url:'https://bjsc.net.cn/bjsc/kdbjkx/kdbjkxwwmxd/wwmxdycwz/wwmxdycdqkj/202603/t20260331_174985.html'}],coordinateNote:'社区山峰资料点位，近鳌山导航架；非实测峰顶定位。'},
 {id:'maijie',name:'麦秸岭',english:'MAIJIE LING',coordinate:{lon:107.48387,lat:33.95441},elevation:3520,kind:'西段 · 认识连续山脊',title:"一道山梁，\n接着另一道山梁。",body:'来到鳌山东侧的麦秸岭。地图上的山脊与沟谷交错展开：认识鳌太，需要记住这些相互连接、又彼此分开的地形，而不只是记住一个山名。',look:'切换立体地形，观察高处向两侧谷地的落差。再回到全貌，辨认刚才看过的鳌山。',transition:'下一章转向太白梁。中间省略飞机梁、金字塔等路段，不表示已经连续走过。',sources:[{label:'PeakWiki · 麦秸岭点位',url:'https://www.peakwiki.org/en/peak.php?pid=476'},{label:'历史记录 · 地名先后关系',url:'https://www.8264.com/youji/2401095.html'}],coordinateNote:'社区山峰资料点位；资料海拔非本项目测量。'},
 {id:'taibailiang',name:'太白梁',english:'TAIBAI LIANG',coordinate:{lon:107.668883,lat:33.917731},elevation:3523,kind:'中东段 · 跨过地图的中部',title:"越过中段，\n太白山成为目标。",body:'太白梁与太白山主峰不是同一个地点。此刻已经从西侧转到地图的中东部；拔仙台仍在更东边，旅程还没有抵达终章。',look:'把太白梁与拔仙台同时放在地图里，辨认两者的相对位置。立体地形只展示高程起伏，不添加未经核实的地标建筑。',transition:'转场到太白山主峰附近。中间的东塬、万仙阵与跑马梁等路段本版不逐段展开。',sources:[{label:'Peakbagger · 太白梁点位',url:'https://www.peakbagger.com/peak.aspx?pid=74763'},{label:'历史记录 · 地名先后关系',url:'https://www.8264.com/youji/2401095.html'}],coordinateNote:'公开山峰数据库 WGS84 点位；用于区域展示，非实地导航。'},
 {id:'dayehai',name:'大爷海',english:'DAYEHAI LAKE',coordinate:{lon:107.7607,lat:33.9573},elevation:3590,kind:'东端 · 主峰旁的高山湖泊',title:"在主峰北侧，\n辨认大爷海。",body:'大爷海是太白山高山区的湖泊，位于拔仙台北侧。地图在这里拉近：湖泊和峰顶相邻，却处在不同高度。记住这对关系，就有了一个具体的地方。',look:'蓝色标记是湖泊位置，不是湖岸轮廓。当前立体地形未复原湖面，避免用虚构湖泊冒充实景。',transition:'最后看向相邻的拔仙台。这里的先湖后峰是本次展览顺序，不代表唯一现实线路。',sources:[forestry,{label:'Mapcarta / OSM · 大爷海点位',url:'https://mapcarta.com/W334814966'}],coordinateNote:'OSM way 334814966 的区域中心点（经 Mapcarta 核对），不是湖岸测量。'},
 {id:'baxiantai',name:'拔仙台',english:'BAXIAN TAI',coordinate:{lon:107.76528,lat:33.95512},elevation:3771,kind:'东端 · 太白山主峰',title:"从鳌山到太白，\n回望刚才的来路。",body:'拔仙台是太白山主峰。本次导览在这里收束：回看西侧的鳌山，麦秸岭与太白梁不再是陌生地名，而成了同一段山地故事中的位置。',look:'选择“回望来路”观察西侧山体，或退回全貌，把五个地点重新连成一段地理记忆。',transition:'地理导览到此结束。认识这片山，不等于完成了现实穿越。',sources:[forestry,{label:'PeakWiki · 拔仙台点位',url:'https://www.peakwiki.org/en/peak.php?pid=39'}],coordinateNote:'社区山峰资料点位；资料海拔按林草局文章约 3771 米呈现。'},
];
export const JOURNEY_NOTICE='地点间虚线仅表示导览顺序与大致方向，不是实测轨迹，也不代表可通行路线。';
